---
exclude:
  - Makefile
  # Exclude symlinks
  - release/1.4.14/index.html
  - release/1.6.1/index.html
  - release/openafs-1.6.0.html
  - release/openafs-1.6.0pre6.html
  - release/openafs-1.6.10.html
  - release/openafs-1.6.11.1.html
  - release/openafs-1.6.11.html
  - release/openafs-1.6.12.html
  - release/openafs-1.6.13.html
  - release/openafs-1.6.14.1.html
  - release/openafs-1.6.14.html
  - release/openafs-1.6.15.html
  - release/openafs-1.6.16.html
  - release/openafs-1.6.17.html
  - release/openafs-1.6.18.1.html
  - release/openafs-1.6.18.2.html
  - release/openafs-1.6.18.3.html
  - release/openafs-1.6.18.html
  - release/openafs-1.6.19.html
  - release/openafs-1.6.2.1.html
  - release/openafs-1.6.20.1.html
  - release/openafs-1.6.20.2.html
  - release/openafs-1.6.20.html
  - release/openafs-1.6.21.1.html
  - release/openafs-1.6.21.html
  - release/openafs-1.6.22.1.html
  - release/openafs-1.6.22.2.html
  - release/openafs-1.6.22.3.html
  - release/openafs-1.6.22.4.html
  - release/openafs-1.6.22.html
  - release/openafs-1.6.23.html
  - release/openafs-1.6.3.html
  - release/openafs-1.6.4.html
  - release/openafs-1.6.5.1.html
  - release/openafs-1.6.5.2.html
  - release/openafs-1.6.5.html
  - release/openafs-1.6.6.html
  - release/openafs-1.6.8.html
  - release/openafs-1.6.9.html
  - release/openafs-1.7.1.html
  - release/openafs-1.8.0.html
  - release/openafs-1.8.0pre1.html
  - release/openafs-1.8.0pre2.html
  - release/openafs-1.8.0pre3.html
  - release/openafs-1.8.0pre4.html
  - release/openafs-1.8.0pre5.html
  - release/openafs-1.8.1.1.html
  - release/openafs-1.8.1.html
  - release/openafs-1.8.1pre2.html
  - release/openafs-1.8.2.html
  - release/openafs-1.8.3pre1.html
